language: php

php:
- '5.6'
- '7.0'

install: [
  "mkdir -p app/etc var",
  "echo \"{\\\"http-basic\\\":{\\\"repo.magento.com\\\":{\\\"username\\\":\\\"${MAGENTO_USERNAME}\\\",\\\"password\\\":\\\"${MAGENTO_PASSWORD}\\\"}}}\" > auth.json",
  "composer require magento/magento2-base --no-update",
  "composer install --prefer-dist"
]

cache:
  directories:
    - $HOME/.composer/cache

script:
    - vendor/bin/phpcs --standard=vendor/smile/magento2-smilelab-phpcs/phpcs-standards/SmileLab --extensions=php src/
    - vendor/bin/phpmd src text vendor/smile/magento2-smilelab-phpmd/phpmd-rulesets/rulset.xml
    - vendor/bin/phpunit -c Resources/tests/unit/phpunit.xml
